# Generated by Django 6.0.4 on 2026-04-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion_Consolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7, unique=True)),
                ('cpu_avg_aws', models.FloatField(default=0.0)),
                ('netout_gb_aws', models.FloatField(default=0.0)),
                ('cpu_avg_gcp', models.FloatField(default=0.0)),
                ('netout_gb_gcp', models.FloatField(default=0.0)),
                ('costo_aws', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_gcp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
